blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Alex-Ratel/tuya-local-apolitical/discussions
    about: Questions and requests for help should be posted in Discussions
